# Generated by Django 2.2.5 on 2019-10-02 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modele', models.CharField(max_length=25)),
                ('date_fabrication', models.DateField()),
                ('hauteur', models.FloatField()),
                ('largeur', models.FloatField()),
                ('poids', models.FloatField()),
                ('puissance', models.IntegerField()),
            ],
            options={
                'verbose_name': 'vehicule',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
                ('id_vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicule.Vehicule')),
            ],
            options={
                'verbose_name': 'photo',
                'ordering': ['id'],
            },
        ),
    ]
