# Generated by Django 2.2.5 on 2019-11-01 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicule',
            name='immatriculation',
            field=models.CharField(default='AA-000-AA', max_length=9),
            preserve_default=False,
        ),
    ]
