# Generated by Django 2.2.5 on 2020-01-26 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agence', '0002_auto_20200126_2000'),
        ('vehicule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicule',
            name='id_agence',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='agence.Agence'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='id_vehicule',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='vehicule.Vehicule'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='url',
            field=models.CharField(default='àremplir', max_length=255),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='date_fabrication',
            field=models.DateField(default='àremplir'),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='hauteur',
            field=models.FloatField(default='àremplir'),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='immatriculation',
            field=models.CharField(default='àremplir', max_length=9),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='largeur',
            field=models.FloatField(default='àremplir'),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='modele',
            field=models.CharField(default='àremplir', max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='poids',
            field=models.FloatField(default='àremplir'),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='puissance',
            field=models.IntegerField(default='àremplir'),
        ),
    ]
