# Generated by Django 2.2.5 on 2020-01-31 19:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicule', '0001_initial'),
        ('agence', '0001_initial'),
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(default='àremplir', max_length=20)),
            ],
            options={
                'verbose_name': 'statut',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Probleme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('probleme', models.TextField(blank=True, default='null', null=True)),
                ('date_signalement', models.DateTimeField(default=datetime.date.today)),
                ('date_resolution', models.DateTimeField(blank=True, default='null', null=True)),
                ('id_agent_ouverture', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='id_agent_ouverture', to='agent.Agent')),
                ('id_agent_resolution', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='id_agent_resolution', to='agent.Agent')),
                ('id_vehicule', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vehicule.Vehicule')),
            ],
            options={
                'verbose_name': 'probleme',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Historique',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateTimeField(default=datetime.date.today)),
                ('date_fin', models.DateTimeField(blank=True, default='null', null=True)),
                ('localisation', models.CharField(default='àremplir', max_length=50)),
                ('id_agence', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='agence.Agence')),
                ('id_agent', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='agent.Agent')),
                ('id_statut', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='historique.Statut')),
                ('id_vehicule', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vehicule.Vehicule')),
            ],
            options={
                'verbose_name': 'historique',
                'ordering': ['id'],
            },
        ),
    ]
