# Generated by Django 2.2.5 on 2019-12-07 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicule', '0001_initial'),
        ('agence', '0001_initial'),
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'statut',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Historique',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
                ('probleme', models.TextField()),
                ('id_agence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agence.Agence')),
                ('id_agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agent.Agent')),
                ('id_statut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='historique.Statut')),
                ('id_vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicule.Vehicule')),
            ],
            options={
                'verbose_name': 'historique',
                'ordering': ['id'],
            },
        ),
    ]
