# Generated by Django 2.2.5 on 2020-01-26 20:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicule', '0002_auto_20200126_2000'),
        ('agent', '0002_auto_20200126_2000'),
        ('historique', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historique',
            name='probleme',
        ),
        migrations.AddField(
            model_name='historique',
            name='localisation',
            field=models.CharField(default='àremplir', max_length=50),
        ),
        migrations.AlterField(
            model_name='historique',
            name='date_debut',
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='historique',
            name='date_fin',
            field=models.DateTimeField(blank=True, default='null', null=True),
        ),
        migrations.AlterField(
            model_name='historique',
            name='id_agence',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='agence.Agence'),
        ),
        migrations.AlterField(
            model_name='historique',
            name='id_agent',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='agent.Agent'),
        ),
        migrations.AlterField(
            model_name='historique',
            name='id_statut',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='historique.Statut'),
        ),
        migrations.AlterField(
            model_name='historique',
            name='id_vehicule',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='vehicule.Vehicule'),
        ),
        migrations.AlterField(
            model_name='statut',
            name='statut',
            field=models.CharField(default='àremplir', max_length=20),
        ),
        migrations.CreateModel(
            name='Probleme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('probleme', models.TextField(blank=True, default='null', null=True)),
                ('date_signalement', models.DateTimeField(default=datetime.date.today)),
                ('date_resolution', models.DateTimeField(blank=True, default='null', null=True)),
                ('id_agent_ouverture', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='id_agent_ouverture', to='agent.Agent')),
                ('id_agent_resolution', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='id_agent_resolution', to='agent.Agent')),
                ('id_vehicule', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='vehicule.Vehicule')),
            ],
            options={
                'verbose_name': 'probleme',
                'ordering': ['id'],
            },
        ),
    ]
