# Generated by Django 2.2.5 on 2020-01-31 19:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agence', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='àremplir', max_length=30)),
                ('prenom', models.CharField(default='àremplir', max_length=30)),
                ('sexe', models.CharField(max_length=1)),
                ('adresse', models.TextField(default='àremplir')),
                ('complement_adresse', models.TextField(blank=True, default='null', null=True)),
                ('code_postal', models.IntegerField(default=0)),
                ('ville', models.CharField(default='àremplir', max_length=20)),
                ('tel', models.CharField(default='àremplir', max_length=15)),
                ('fax', models.CharField(blank=True, default='null', max_length=15, null=True)),
                ('mobile', models.CharField(blank=True, default='null', max_length=15, null=True)),
                ('email', models.CharField(default='àremplir', max_length=50)),
                ('date_entree_socopec', models.DateField(default=datetime.date.today)),
                ('poste_socopec', models.CharField(default='àremplir', max_length=30)),
                ('admin', models.BooleanField(default=False)),
                ('identifiant', models.CharField(default='àremplir', max_length=20)),
                ('mot_de_passe', models.CharField(default='àremplir', max_length=20)),
                ('photo', models.CharField(blank=True, default='null', max_length=255, null=True)),
                ('id_agence', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='agence.Agence')),
            ],
            options={
                'verbose_name': 'agent',
                'ordering': ['id'],
            },
        ),
    ]
