# Generated by Django 2.2.5 on 2020-01-26 20:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='login',
        ),
        migrations.AddField(
            model_name='agent',
            name='adresse',
            field=models.TextField(default='àremplir'),
        ),
        migrations.AddField(
            model_name='agent',
            name='code_postal',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='agent',
            name='complement_adresse',
            field=models.TextField(blank=True, default='null', null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='date_entree_socopec',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='agent',
            name='email',
            field=models.CharField(default='àremplir', max_length=50),
        ),
        migrations.AddField(
            model_name='agent',
            name='identifiant',
            field=models.CharField(default='àremplir', max_length=20),
        ),
        migrations.AddField(
            model_name='agent',
            name='photo',
            field=models.CharField(blank=True, default='null', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='poste_socopec',
            field=models.CharField(default='àremplir', max_length=30),
        ),
        migrations.AddField(
            model_name='agent',
            name='ville',
            field=models.CharField(default='àremplir', max_length=20),
        ),
        migrations.AlterField(
            model_name='agent',
            name='fax',
            field=models.CharField(blank=True, default='null', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='id_agence',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='agence.Agence'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='mobile',
            field=models.CharField(blank=True, default='null', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='mot_de_passe',
            field=models.CharField(default='àremplir', max_length=20),
        ),
        migrations.AlterField(
            model_name='agent',
            name='nom',
            field=models.CharField(default='àremplir', max_length=30),
        ),
        migrations.AlterField(
            model_name='agent',
            name='prenom',
            field=models.CharField(default='àremplir', max_length=30),
        ),
        migrations.AlterField(
            model_name='agent',
            name='tel',
            field=models.CharField(default='àremplir', max_length=15),
        ),
    ]
