# Generated by Django 2.2.5 on 2020-01-26 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0002_auto_20200126_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='id_agence',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='agence.Agence'),
        ),
    ]
