# Generated by Django 2.2.5 on 2019-11-02 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0002_agent_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='id_agence',
        ),
    ]
