# Generated by Django 2.2.5 on 2020-01-31 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='à remplir', max_length=30)),
                ('adresse', models.TextField(default='à remplis')),
                ('complement_adresse', models.TextField(blank=True, default='null', null=True)),
                ('code_postal', models.IntegerField(default=0)),
                ('ville', models.CharField(default='default_city', max_length=20)),
                ('telephone', models.CharField(default='à remplir', max_length=15)),
                ('fax', models.CharField(blank=True, default='null', max_length=15, null=True)),
                ('photo', models.CharField(blank=True, default='null', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'agence',
                'ordering': ['id'],
            },
        ),
    ]
