# Generated by Django 2.2.5 on 2019-12-07 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.CharField(max_length=255)),
                ('nom', models.CharField(max_length=50)),
                ('adresse', models.TextField()),
                ('tel', models.CharField(max_length=15)),
                ('fax', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name': 'agence',
                'ordering': ['id'],
            },
        ),
    ]
