# Generated by Django 2.2.5 on 2019-10-02 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('adresse', models.TextField()),
                ('tel', models.CharField(max_length=15)),
                ('fax', models.CharField(max_length=15)),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicule.Photo')),
            ],
            options={
                'verbose_name': 'agence',
                'ordering': ['id'],
            },
        ),
    ]
