# Generated by Django 2.2.5 on 2020-01-26 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agence', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agence',
            name='tel',
        ),
        migrations.AddField(
            model_name='agence',
            name='code_postal',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='agence',
            name='complement_adresse',
            field=models.TextField(blank=True, default='null', null=True),
        ),
        migrations.AddField(
            model_name='agence',
            name='telephone',
            field=models.CharField(default='à remplir', max_length=15),
        ),
        migrations.AddField(
            model_name='agence',
            name='ville',
            field=models.CharField(default='default_city', max_length=20),
        ),
        migrations.AlterField(
            model_name='agence',
            name='adresse',
            field=models.TextField(default='à remplis'),
        ),
        migrations.AlterField(
            model_name='agence',
            name='fax',
            field=models.CharField(blank=True, default='null', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='agence',
            name='nom',
            field=models.CharField(default='à remplir', max_length=30),
        ),
        migrations.AlterField(
            model_name='agence',
            name='photo',
            field=models.CharField(blank=True, default='null', max_length=255, null=True),
        ),
    ]
